steps:
  - name: golang:1.19
    entrypoint: go
    args: ["mod", "download"]

  - name: golang:1.19
    entrypoint: go
    args: ["test", "./..."]

      # NOTE the pipeline requires the repository to exist and be exported as
      # env var here

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}',
      '.',
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}']

  - name: google/cloud-sdk
    args: [
      'gcloud',
      'run',
      'deploy',
      'helloworld-${SHORT_SHA}',
         '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}',
         '--region=us-central1',
         '--platform=managed',
         # edit below to prevent unauthenticated access
         '--allow-unauthenticated',
      ]

options:
  env:
    - 'PUT_VALUES=here'
